# Workflow name
name: model-training

# trigger
on:
  pull_request:
    branches: main

# Permissions
permissions:
  pull-requests: write
  contents: write

# Jobs and runner
jobs:
  train_and_report_eval_performance:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: true

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Setup CML
        uses: iterative/setup-cml@v1

      - name: Pull DVC Data
        run: dvc pull --force

      - name: Run DVC Pipeline
        run: dvc repro

      - name: Write CML Report
        env:
          REPO_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          cat metrics.json >> model_eval_report.md
          echo "![confusion matrix plot](./confusion_matrix.png)" >> model_eval_report.md
          cml comment create model_eval_report.md
